# Game Theory With Python

### Welcome to the course. 
### Glad to have you onboard in this journey to explore two Game Theory packages in Python

#### Nashpy & Axelrod

#### 7 Tasks
#### 1. Create games with Nashpy
#### 2. Mixed strategies and Utilities
#### 3. Nash Equilibrium
#### 4. Games with multiple Nash Equilibria
#### 5. Zero Sum Game
#### 6. Create repeated game
#### 7. Analyze Match

## Two Player Games with Nashpy

## 1. Create 2 player games - Using Nashpy
The Goal here is to learn how to create games based on payoff matrices!
### Consider the following Prisoner's Dilemma matrix

![picture](img/img1.png)


In [1]:
import nashpy as nash
import numpy as np

Pay off will be stored for each player in a numpy matrix and then passed to a `Game` object from the `nash` module

In [2]:
# Create the payoff matrix

P1 = np.array([[8,1],[15,3]]) #row player
P2 = np.array([[8,15],[1,3]]) # column player
pdi = nash.Game(P1,P2)
pdi


Bi matrix game with payoff matrices:

Row player:
[[ 8  1]
 [15  3]]

Column player:
[[ 8 15]
 [ 1  3]]

### Exercise: Create a two player game, where,

#### I. Name players as A and B
#### II. Name the game as 'gm' and 
#### III. Use the follwing matrix

![picture](./img/img2.PNG)


In [3]:
PA = np.array([[5,17],[14,12]])
PB = np.array([[15,16],[2,8]])
gm = nash.Game(PA,PB)
gm

Bi matrix game with payoff matrices:

Row player:
[[ 5 17]
 [14 12]]

Column player:
[[15 16]
 [ 2  8]]

## 2. Mixed Strategy and Utilities

### Pure Strategy: 

A complete definition of how a player will play a game, it yields optimum payoff to the player. 

### Mixed Strategy: 

Assigns a probability to each pure strategy. This allows for a player to randomly select a pure strategy. 

### Calculating Utilities:

![picture](img/img3.png)

#### Consider the following Mixed Strategy

σr=(.2,.8) and σc=(.6,.4)


We now calculate the utilities for the mixed strategies by putting the coeficient into numpy array and scripting them from the game

In [4]:
# Calculate Utilities

sigma_r = np.array([0.2,.8])
sigma_c = np.array([.6,.4])
pdi = nash.Game(P1, P2)
pdi[sigma_r, sigma_c]

array([9.2, 3.6])

In [6]:
#ur(σr,σc)
ur=0.2*0.6*8+0.2*0.4*1+0.8*0.6*15+0.8*0.4*3
ur

9.2

In [7]:
#uc(σr,σc)
uc=0.2*0.6*8+0.2*0.4*15+0.8*0.6*1+0.8*0.4*3
uc

3.6000000000000005

### Exercise: Calculate the utilities of the game 'gm' created in the previous exercise, using 
#### σr=(.3,.7) and σc=(.5,.5)

In [8]:
sigma_A = np.array([0.3,.7])
sigma_B = np.array([.5,.5])
gm = nash.Game(PA, PB)
gm[sigma_A, sigma_B]

array([12.4 ,  8.15])

## 3. The Nash Equilibrium

Strict and unique Nash Equilibrium

![picture](img/img4.png)

In [10]:
# Find the Nash Equilibrium with Support Enumeration

equilibria = pdi.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))


#### Both solutions match

### Exercise: Find out the Nash Equilibrium for gm

In [11]:
for eq in gm.support_enumeration():
    print(eq)

(array([1., 0.]), array([0., 1.]))


## 4. Games with Multiple Nash Equilibria

### Hawk - Dove Game

![picture](img/img5.png)

In [13]:
P3 =  np.array([[3,1],[4,0]]) #P3 is p1 in image
P4 =  np.array([[3,4],[1,0]])# P4 is the column player (p2 in image
hd = nash.Game(P3,P4)
hd

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [4 0]]

Column player:
[[3 4]
 [1 0]]

#### Nash Equilibria

![picture](img/img6.png)


In [14]:
equilibria = hd.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.5, 0.5]), array([0.5, 0.5]))


Sol. (D,H)

P3 : D = 1, H = 0

P4 : D = 0, H = 1

Sol. (H,D)

P3 : D = 0, H = 1

P4 : D = 1, H = 0

Sol. (D,D) or (H,H)

P3 : D = 0.5, H = 0.5

P4 : D = 0.5, H = 0.5


### Exercise: Find out the number of NE for the following matrix
#### Players: M and N
#### Name of game mn


![picture](img/img7.png)

In [17]:
PM=np.array([[1,1,3,2],[2,3,4,3],[5,1,1,4]])
PN=np.array([[3,2,2,4],[1,4,2,0],[3,3,2,3]])
g2=nash.Game(PM,PN)
g2

Bi matrix game with payoff matrices:

Row player:
[[1 1 3 2]
 [2 3 4 3]
 [5 1 1 4]]

Column player:
[[3 2 2 4]
 [1 4 2 0]
 [3 3 2 3]]

In [18]:
for eq in g2.support_enumeration():
    print(eq)

(array([0., 1., 0.]), array([0., 1., 0., 0.]))
(array([0., 0., 1.]), array([1., 0., 0., 0.]))
(array([0., 0., 1.]), array([0., 0., 0., 1.]))


![picture](img/img8.png)

## 5. Zero Sum Game

Matching the pennies game

![picture](img/5-1.png)

In [19]:
P5 = np.array([[1,-1],[-1,1]])
mp = nash.Game(P5)
mp

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [20]:
for eq in mp.support_enumeration():
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


### Exercise: Find out the solution for the following zero sum game 'zs'
#### Use payoff matrix - np.array([[5, -6.5], [-2.5, 7]]) 
#### For players Z1 and Z2

In [21]:
PO = np.array([[5, -6.5], [-2.5, 7]])
zs = nash.Game(PO)
zs

Zero sum game with payoff matrices:

Row player:
[[ 5.  -6.5]
 [-2.5  7. ]]

Column player:
[[-5.   6.5]
 [ 2.5 -7. ]]

In [22]:
for eq in zs.support_enumeration():
    print (eq)

(array([0.45238095, 0.54761905]), array([0.64285714, 0.35714286]))


## Two Player-Repeated Games with Axelrod

## 6. Create repeated game

In [26]:
#!pip install -U pyYAML     # Troubleshoot: Execute this line if Axelrod does not run and AttributeError: module 'yaml' has no attribute 'FullLoader' occurs

import axelrod as axl

In [29]:
# Create matches

players = (axl.Cooperator(),axl.Alternator())                  # using players of Cooperator and Alternator strategy
match1 =   axl.Match(players, turns = 5)                          # play for 5 turns
match1.play()

[(C, C), (C, D), (C, C), (C, D), (C, C)]

In [28]:
axl.all_strategies

[axelrod.strategies.memoryone.ALLCorALLD,
 axelrod.strategies.memorytwo.AON2,
 axelrod.strategies.apavlov.APavlov2006,
 axelrod.strategies.apavlov.APavlov2011,
 axelrod.strategies.adaptive.Adaptive,
 axelrod.strategies.titfortat.AdaptiveTitForTat,
 axelrod.strategies.adaptor.AdaptorBrief,
 axelrod.strategies.adaptor.AdaptorLong,
 axelrod.strategies.grudger.Aggravater,
 axelrod.strategies.titfortat.Alexei,
 axelrod.strategies.alternator.Alternator,
 axelrod.strategies.hunter.AlternatorHunter,
 axelrod.strategies.cycler.AntiCycler,
 axelrod.strategies.titfortat.AntiTitForTat,
 axelrod.strategies.appeaser.Appeaser,
 axelrod.strategies.qlearner.ArrogantQLearner,
 axelrod.strategies.averagecopier.AverageCopier,
 axelrod.strategies.backstabber.BackStabber,
 axelrod.strategies.better_and_better.BetterAndBetter,
 axelrod.strategies.titfortat.Bully,
 axelrod.strategies.bush_mosteller.BushMosteller,
 axelrod.strategies.calculator.Calculator,
 axelrod.strategies.grudger.Capri,
 axelrod.strategies

### Exercise: Create a repeated game with 2 players having:
#### I. TitForTat and Random Strategy 
#### II. Name it as match2
#### III. Run it for 15 turns

In [30]:
players2=(axl.TitForTat(),axl.Random())
match2= axl.Match(players2,turns=15)
match2.play()

[(C, C),
 (C, D),
 (D, C),
 (C, C),
 (C, C),
 (C, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, D),
 (D, C),
 (C, D),
 (D, D),
 (D, C)]

## 7. Analyze Match

In [33]:
# Payoffs

match1.game       #Analyze the match

#These payoffs are commonly referred to as:

#R: the Reward payoff (default value in the library: 3) C-C
#P: the Punishment payoff (default value in the library: 1) D-D
#S: the Loss payoff (default value in the library: 0) C-D
#T: the Temptation payoff (default value in the library: 5) D-C

Axelrod game: (R,P,S,T) = (3, 1, 0, 5)

In [34]:
# Scores of a match

match1.scores()     #Retrieve match scores

[(3, 3), (0, 5), (3, 3), (0, 5), (3, 3)]

In [37]:
# The result of the match can also be viewed as sparklines where cooperation is shown as a solid block and defection as a space. (in pycharm dark theme blocks are white and space are dark)

print(match1.sparklines())  # Get output using sparklines

█████
█ █ █


### Exercise: Analyze match2. 
#### Find the score and create the sparklines

In [38]:
match2.scores()

[(3, 3),
 (0, 5),
 (5, 0),
 (3, 3),
 (3, 3),
 (0, 5),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (5, 0),
 (0, 5),
 (1, 1),
 (5, 0)]

In [39]:
print(match2.sparklines())

██ ███      █  
█ ███      █  █


#### References:

Package Documentations

https://nashpy.readthedocs.io/en/stable/index.html#

https://axelrod.readthedocs.io/en/stable/#

## quizz coding
### Q1
![image](img/A1Q1.png)

In [23]:
A=np.array([[100,35],[175,50]])
B=np.array([[100,175],[35,50]])
game_q1=nash.Game(A,B)
game_q1

Bi matrix game with payoff matrices:

Row player:
[[100  35]
 [175  50]]

Column player:
[[100 175]
 [ 35  50]]

### Q2
![](img/A1Q2.png)

In [24]:
for eq in game_q1.support_enumeration():
    print(eq)

(array([0., 1.]), array([0., 1.]))


### Q3
![](img/A1Q3.png)

In [25]:
sigma_A=np.array([.3,.7])
sigma_B=np.array([.6,.4])
game_q1[sigma_A,sigma_B]

array([109.7,  67.7])

### Q4
![](img/A1Q4.png)



In [46]:
print("option1")
print(9*'-')
players = (axl.Alternator(),axl.TitForTat())
match= axl.Match(players,turns=12)
match.play()
print(match.sparklines())
print(15*'=')


print("option2")
print(9*'-')
players = (axl.TitForTat(),axl.Alternator())
match= axl.Match(players,turns=12)
match.play()
print(match.sparklines())
print(15*'=')


print("option3")
print(9*'-')
players = (axl.Cooperator(),axl.Defector())
match= axl.Match(players,turns=12)
match.play()
print(match.sparklines())
print(15*'=')


print("option4")
print(9*'-')
players = (axl.Defector(),axl.Defector())
match= axl.Match(players,turns=12)
match.play()
print(match.sparklines())
print(15*'=')


option1
---------
█ █ █ █ █ █ 
██ █ █ █ █ █
option2
---------
██ █ █ █ █ █
█ █ █ █ █ █ 
option3
---------
████████████
            
option4
---------
            
            


### Q5
![](img/A1Q5.png)